### ISSUE TITLE
help required in starting it

### ISSUE THREAD

**Issue by techguy07** [jpmens/from-traccar#2]
Dear Jpmen, 

thanks for amazing script , actually i was looking to integrate it with voip service and generate calls on events, 
I am getting issue while starting it, Mosquito is installed , screenshot of error attached it says
./ft-run.sh: 6: ./ft-run.sh: ./ft: not found

https://www.dropbox.com/s/ey86bzgqpr23dgk/Screenshot%202019-04-19%2011.36.30.png?dl=0

**Comment by jpmens** [comment]
That screenshot is not visible. If you think it important you can drag the image into an issue here.

**Comment by techguy07** [comment]
<img width="831" alt="Screenshot 2019-04-19 11 36 30" src="https://user-images.githubusercontent.com/49776030/56411957-003e1680-629c-11e9-942b-574d428cb6a1.png">

**Comment by jpmens** [comment]
I assume you created `ft-run.sh` from our `ft-run.sample`. The file name suggests that it is a **sample**, and that you modify it to suit your environment.

In essence, copy the binary `ft` to a location which suits youi, adjust `ft-run.sh` accordingly, and then see what happens.

Note, without basic Unix/Linux sysadmin knowledge you are going to have a difficult time with this.

**Comment by techguy07** [comment]
Exactly this is what i did, and honesly i dnt have much knowledge of sysadmin that why having hard time

**Comment by jpmens** [comment]
Your screenshot suggests you haven't compiled the program. You will have to install the dependencies (hints in the README) and then type `make`.

I think you should start by telling me what you actually intend to use this program for as it might be much more work for you than you anticipate. Tell me a good story, and I might be tempted to guide you further. :-)

**Comment by techguy07** [comment]
Basically I need all data of Events to hit asterisk server and Generate call via sip on **GeoFense out** and on **Power Temper Alarm** Alert.

**Comment by jpmens** [comment]
(I think your text is truncated)

**Comment by jpmens** [comment]
This program is not what you need for that, or rather, I think you are addressing this in a too complicated way. I'd like to make a small suggestion which I believe will be more along the lines of what you intend to accomplish. (It greatly saddens me that I'm suggesting a solution without using MQTT, but I know life can be harsh and brutal.)

If I were you I'd take the route of [Asterisk Call Files](https://www.voip-info.org/asterisk-auto-dial-out) which ought to be easy to comprehend. Basically, you create a text file with some commands in it which Asterisk understands, place the file in the correct directory, and Asterisk picks it up and dials the number. So far the theory, but I've not a clue about Asterisk, so you'll have to experiment.

Once you get that going just by creating a file in a text editor and testing that it actually works, what I would do is to have a minimal HTTP server to which your Traccar speaks. Something in PHP on your Web server would do, or something in Python such as this simple example:

```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from bottle import run, request, post, response, HTTPResponse
from string import Template
import json

# Slapped together by jpmens on 2019-04-20

@post('/event')
def traccar_event():

    # https://www.voip-info.org/asterisk-auto-dial-out
    templ = Template("""Channel: $channel
Callerid: $callerid
Application: Playback
Data: $message
""")

    postdata = request.body.read()

    try:
        data = json.loads(postdata)
    except Exception as e:
        print("Could not JSON decode %s: %s" % (postdata, str(e)))
        return HTTPResponse(status=500, body="Can't decode JSON")


    if "event" in data and "type" in data["event"]:
        event = data["event"]["type"]
        if "device" in data and "name" in data["device"]:
            device_name = data["device"]["name"]

            print(device_name, event)

            data = {
                "channel"       : "SIP/1234567890",
                "callerid"      : "my number",
                "message"       : "device {0} has exited geofence".format(device_name),
            }

            with open("event.call", "w") as f:
                f.write(templ.substitute(**data))

    return ""


run(host='127.0.0.1', port=8849, debug=True)
```

(You store that in a file called, say, `traccar-events.py` and `chmod +x traccar-events.py` to make it executable. you can then launch it with `./traccar-events.py`)

On the Traccar side, you configure event forwarding which will cause the program to POST events to the specified address; that's where your little server is listening:

```xml
<!-- event forwarding -->
<entry key="event.forward.enable">true</entry>
<entry key='event.forward.url'>http://127.0.0.1:8849/event</entry>
```

As soon as Traccar sends an event, `geofenceExit`, say, you'll see in the current directory a file `event.call` which was created by the Python program:

```
Channel: SIP/1234567890
Callerid: my number
Application: Playback
Data: device Demo-54 has exited geofence
```

If you then ensure that that file is placed in the correct directory for Asterisk, you should be on the way to being able to automate outgoing calls on Traccar events.

Do note that this is untested. Your explanation piqued my interest, which is why I spent a few minutes trying to find a solution for you. Good luck!

**Comment by techguy07** [comment]
Thankyou so much @jpmens for spending time on this, yes i am going to use asterisk Call files.
Will keep you posted.

**Comment by techguy07** [comment]
@jpmens I m successful in generating call from asterisk already, by putting .call file into outgoing folder, Python bottle server is also up and getting hits of events

**Comment by techguy07** [comment]
I have configured and executed the sample example you posted above in python, but when it receive post data from traccar log shows POST /event/ HTTP/1.1" 404 736 error

**Comment by jpmens** [comment]
404 means “not found”. I think you have a trailing slash in traccar.xml and not in the python program. Make sure they match.

**Comment by techguy07** [comment]
yes got it working now, Just two issue now, Would like to have Random File name or in Sequence number to copy to outgoing folder so i can be archived, Additionally, I need Phone number of user also to generate call to him on geofense out.

**Comment by jpmens** [comment]
I'm glad you got it to work.

And now it's your turn to do a bit of homework. :-) I think you should be able to add these things yourself with some study.

1. The random file you can generate in the Python code. See if you can replace the hard-coded `event.call` filename. Your Internet search engine of choice will be of assistance.
2. The second is a bit harder, but also fun to do: if I recall correctly, Traccar hands over a user's configured phone number in the JSON payload your small Python program is now getting. Put a `print(postdata)` after the line `postdata = request.body.read()` to see it on the console. You find the object it's in and extract it similarly to the way I've done for `device_name` and `event` and use the obtained phone number in the `data` dict when setting `channel : xxxxx,`

**Comment by vegellibert** [comment]
> I'm glad you got it to work.
> 
> And now it's your turn to do a bit of homework. :-) I think you should be able to add these things yourself with some study.
> 
> 1. The random file you can generate in the Python code. See if you can replace the hard-coded `event.call` filename. Your Internet search engine of choice will be of assistance.
> 2. The second is a bit harder, but also fun to do: if I recall correctly, Traccar hands over a user's configured phone number in the JSON payload your small Python program is now getting. Put a `print(postdata)` after the line `postdata = request.body.read()` to see it on the console. You find the object it's in and extract it similarly to the way I've done for `device_name` and `event` and use the obtained phone number in the `data` dict when setting `channel : xxxxx,`

**Comment by vegellibert** [comment]
You rock, and don't you forget it :)
