### ISSUE TITLE
ensure nothing emitted to stdout by mistake

### ISSUE THREAD

**Issue by jpmens** [jpmens/from-traccar#7]
There's a report of occasional messages in the Traccar logs saying

```
2022-10-03 10:07:43  WARN: Event forwarding failed - MessageBodyReader not found for media type=text/plain, type=class java.lang.Object, genericType=class java.lang.Object. - MessageBodyProviderNotFoundException (...)
```

The only cause I can imagine is there are still a few `printf()` in the code. Remove those to be sure we really only send back HTTP headers and body.

**Comment by ckrey** [comment]
The problem occurs because ft.c returns "text/plain" rather than "application/json". No clue why the WARN message
in traccar appears when the event payload is short (no position included).

Event and position forwarding changed a bit in traccar 4.12 in December 2020: https://github.com/traccar/traccar/commit/bc3b09e48efb9a58d9aef111d4316dcd9c0a7038
